### ISSUE TITLE
content/post/dirty_filepath.md: report upstream

### ISSUE THREAD

**Issue by ghost** [kriive/kriive.github.io#1]
have you reported the issue upstream?

https://github.com/golang/go

**Comment by kriive** [comment]
It's not really an issue, it's more of a developers' misuse and misunderstanding of the filepath.Clean API. I don't really know what to suggest them apart from a docs clarification.

**Comment by kriive** [comment]
And they already reported this: https://github.com/golang/go/issues/34938
